"""
output/report.py

Report node + render_report utility.

report_node   — LangGraph node, final step in the graph.
                Builds the full Markdown report from state and writes
                it to state["final_report"].

render_report — called by main.py after graph.invoke() completes.
                Writes the Markdown string to disk and prints a summary
                to the terminal via rich (falls back to plain print).

Report structure:
    # AI Company Builder Report
    ## Executive Summary
    ## Startup Brief          ← synthesis from synthesis_node
    ## Viability Scorecard    ← appended to synthesis by evaluator_node
    ## Guardrail Flags        ← from state["guardrail_flags"]
    ## Errors & Warnings      ← from state["errors"]
    ## Metadata
"""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path
from typing import TYPE_CHECKING

from graph.state import CompanyState

if TYPE_CHECKING:
    pass


# ── report builder ────────────────────────────────────────────────────────────

def _build_report(state: CompanyState) -> str:
    """
    Assembles the full Markdown report string from state.
    Called by both report_node (graph) and render_report (disk write).
    """
    now = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M UTC")
    idea = state.get("idea", "Not provided")
    domain = state.get("domain", "Healthcare / MedTech")
    score = state.get("viability_score")
    flags = state.get("guardrail_flags") or []
    errors = state.get("errors") or []
    synthesis = state.get("synthesis") or "_No synthesis available._"

    # ── score badge ───────────────────────────────────────────────────────────
    if score is None:
        score_badge = "N/A"
        verdict_label = "EVALUATION SKIPPED"
    elif score >= 75:
        score_badge = f"🟢 {score}/100"
        verdict_label = "STRONG"
    elif score >= 55:
        score_badge = f"🟡 {score}/100"
        verdict_label = "PROMISING"
    elif score >= 35:
        score_badge = f"🟠 {score}/100"
        verdict_label = "NEEDS WORK"
    else:
        score_badge = f"🔴 {score}/100"
        verdict_label = "NOT VIABLE"

    # ── flags section ─────────────────────────────────────────────────────────
    if flags:
        critical = [f for f in flags if "critical" in f.lower()]
        warnings = [f for f in flags if "warning" in f.lower()]
        info     = [f for f in flags if f not in critical and f not in warnings]

        flags_md = ""
        if critical:
            flags_md += "### 🚨 Critical\n" + "\n".join(f"- {f}" for f in critical) + "\n\n"
        if warnings:
            flags_md += "### ⚠️ Warnings\n" + "\n".join(f"- {f}" for f in warnings) + "\n\n"
        if info:
            flags_md += "### ℹ️ Info\n" + "\n".join(f"- {f}" for f in info) + "\n\n"
    else:
        flags_md = "_No flags raised. ✅_\n"

    # ── errors section ────────────────────────────────────────────────────────
    errors_md = (
        "\n".join(f"- {e}" for e in errors)
        if errors
        else "_No errors._"
    )

    # ── executive summary ─────────────────────────────────────────────────────
    exec_summary = (
        f"This report was generated by the AI Company Builder multi-agent system. "
        f"The startup idea was analysed across four dimensions — market, clinical research, "
        f"product, and architecture — by parallel AI agents powered by Gemini. "
        f"The viability score is **{score_badge}** ({verdict_label}). "
        f"{len(flags)} compliance/risk flag(s) were raised."
    )

    # ── assemble ──────────────────────────────────────────────────────────────
    report = f"""# AI Company Builder Report

**Generated**: {now}
**Domain**: {domain}
**Viability Score**: {score_badge} — {verdict_label}

---

## Executive Summary

{exec_summary}

---

## Full Analysis

{synthesis}

---

## Guardrail Flags

{flags_md}

---

## Errors & Warnings

{errors_md}

---

## Metadata

| Field | Value |
|-------|-------|
| Generated at | {now} |
| Domain | {domain} |
| Viability score | {score_badge} |
| Flags raised | {len(flags)} |
| Agent errors | {len(errors)} |
| Report version | 1.0 |

---
_Generated by AI Company Builder · LangGraph + Gemini · Healthcare/MedTech_
"""
    return report


# ── LangGraph node ────────────────────────────────────────────────────────────

def report_node(state: CompanyState) -> dict:
    """
    LangGraph node — final step in the graph.
    Builds the Markdown report and writes it to state["final_report"].
    """
    print("[report] Building final report...")
    report_md = _build_report(state)
    print(f"[report] Done. Report is {len(report_md)} chars.")
    return {"final_report": report_md}


# ── disk writer (called by main.py) ──────────────────────────────────────────

def render_report(state: CompanyState, output_path: Path) -> None:
    """
    Writes the final report to disk as Markdown.
    Uses state["final_report"] if available, otherwise builds it fresh.
    Falls back to rich for pretty terminal printing if installed.
    """
    report_md = state.get("final_report") or _build_report(state)

    output_path = Path(output_path)
    output_path.parent.mkdir(parents=True, exist_ok=True)
    output_path.write_text(report_md, encoding="utf-8")

    # ── pretty terminal preview (first 30 lines) ──────────────────────────────
    try:
        from rich.console import Console
        from rich.markdown import Markdown
        console = Console()
        preview_lines = "\n".join(report_md.splitlines()[:30])
        console.print("\n[bold green]── Report Preview (first 30 lines) ──[/bold green]")
        console.print(Markdown(preview_lines))
    except ImportError:
        # rich not installed — plain print fallback
        print("\n── Report Preview ──")
        print("\n".join(report_md.splitlines()[:20]))